// Generated by gencpp from file sudoku_fact_generator/grid_fact.msg
// DO NOT EDIT!


#ifndef SUDOKU_FACT_GENERATOR_MESSAGE_GRID_FACT_H
#define SUDOKU_FACT_GENERATOR_MESSAGE_GRID_FACT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sudoku_fact_generator
{
template <class ContainerAllocator>
struct grid_fact_
{
  typedef grid_fact_<ContainerAllocator> Type;

  grid_fact_()
    : X(0)
    , Y(0)
    , Z(0)  {
    }
  grid_fact_(const ContainerAllocator& _alloc)
    : X(0)
    , Y(0)
    , Z(0)  {
  (void)_alloc;
    }



   typedef int32_t _X_type;
  _X_type X;

   typedef int32_t _Y_type;
  _Y_type Y;

   typedef int32_t _Z_type;
  _Z_type Z;





  typedef boost::shared_ptr< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> const> ConstPtr;

}; // struct grid_fact_

typedef ::sudoku_fact_generator::grid_fact_<std::allocator<void> > grid_fact;

typedef boost::shared_ptr< ::sudoku_fact_generator::grid_fact > grid_factPtr;
typedef boost::shared_ptr< ::sudoku_fact_generator::grid_fact const> grid_factConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sudoku_fact_generator::grid_fact_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sudoku_fact_generator::grid_fact_<ContainerAllocator1> & lhs, const ::sudoku_fact_generator::grid_fact_<ContainerAllocator2> & rhs)
{
  return lhs.X == rhs.X &&
    lhs.Y == rhs.Y &&
    lhs.Z == rhs.Z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sudoku_fact_generator::grid_fact_<ContainerAllocator1> & lhs, const ::sudoku_fact_generator::grid_fact_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sudoku_fact_generator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5d94d1f3fbdaeb95ae7a7c8fead8a5b";
  }

  static const char* value(const ::sudoku_fact_generator::grid_fact_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5d94d1f3fbdaeb9ULL;
  static const uint64_t static_value2 = 0x5ae7a7c8fead8a5bULL;
};

template<class ContainerAllocator>
struct DataType< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sudoku_fact_generator/grid_fact";
  }

  static const char* value(const ::sudoku_fact_generator::grid_fact_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 X\n"
"int32 Y\n"
"int32 Z\n"
;
  }

  static const char* value(const ::sudoku_fact_generator::grid_fact_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.Z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grid_fact_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sudoku_fact_generator::grid_fact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sudoku_fact_generator::grid_fact_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<int32_t>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUDOKU_FACT_GENERATOR_MESSAGE_GRID_FACT_H
